### PR TITLE
Generic CSV Harvester - DRAFT PR

### PR DESCRIPTION
**Pull request by ndhogan**
For https://github.com/aodn/backlog/issues/3149

Still to do:
- [ ] finalise the pipeline location and/or environment variable for public-schema and db connection strings - these are dependent on outstanding chef changes
- [ ] build the tableschema validation in check step - future iteration
- [ ] build the geonetwork extents update function - future iteration

### CODE REVIEW

**Comment by lbesnard** [comment]
@ndhogan Is this for pre-review? I'm not involved in the dev of the generic CSV harvester. I guess @mhidas is, but I have a few comments for this PR:
- there aren't any unittests 
- docstrings/comments are generally missing (I think they are semi-automatically used in the generation of the doc, https://aodn.github.io/python-aodncore/index.html)
- are we going to use liquibase and keep the same existing common tables (such as indexed_file) available in each schema?

**Comment by lbesnard** [comment]
also FYI, I see you wanted to use environment variables. Correct me if I'm wrong, but I think for this we usually use variables defined in chef-private under https://github.com/aodn/chef-private/blob/master/data_bags/pipeline/pipeline_conf_rc.json

**Comment by ndhogan** [comment]
@mhidas

### Steps to run
1. Run up a stack, etc...
2. Create a config file at "chef/private_sample/data_bags/imos_po_watches/[pipelineName].json" (see _BGC.json_ below)
    * _harvest_params_  schema validation also allows an _ingest_type_ attribute (eg. "replace", "truncate", "append") but the harvester will just use "replace" if this isn't provided.
    * also remember, the order of objects in the _db_objects_ array is the order in which the harvest runner will process them.
2. Create a new handler at "chef/src/python-aodndata/[pipelineName]/handler.py" (see _handler.py_)
3. Create the database schema and user (see _bgc.sql_) - change the hostname and other values as appropriate
4. Clone the public-schema directory to "chef/src/schema_definitions/public-schema" (so it is accessible in the pipeline box at "/vagrant/src/schema_definitions/public-schema") - I actually used the mock public-schema directory that I had created for the original harvester prototype (and used them with the data files in that prototype to test this pipeline)
5. On the pipeline box, create a file at "/usr/local/harvester/[schemaName]/database.json" (note __schemaName__ not __pipelineName__) - at the moment this needs to be case sensitive to the _db_schema_ attribute in step 2 above
6. Add the handler reference to "chef/src/python-aodndata/setup.py" --> ENTRY_POINTS --> 'pipeline.handlers', eg _'BgcHandler = aodndata.bgc.handler:BgcHandler'_

### Additional
I looked into applying the _missingValues_ from the schema definition file to the COPY FROM transaction, but postgresql only allows a single null substition (using the format _with null as [yourNullValue]_) - so we might need to think some more about how we'll address this...

Let me know if I've missed anything out.


_BGC.json_
```json
{
    "id": "BGC",
    "path": [ "BGC" ],
    "handler": "BgcHandler",
    "params": {
        "include_regexes": [
            ".*\\.csv$"
        ],
        "harvest_params": {
            "db_schema": "bgc",
            "db_objects": [
                {
                    "name": "bgc_phyto_changelog",
                    "type": "table"
                },
                {
                    "name": "bgc_phyto_raw",
                    "type": "table"
                },
                {
                    "name": "bgc_trip",
                    "type": "table"
                },
                {
                    "name": "bgc_zoop_changelog",
                    "type": "table"
                },
                {
                    "name": "bgc_zoop_raw",
                    "type": "table"
                },
                {
                    "name": "bgc_phyto_aggregation",
                    "type": "materialized view",
                    "dependencies": ["bgc_phyto_raw"]
                },
                {
                    "name": "bgc_zoop_aggregation",
                    "type": "materialized view",
                    "dependencies": ["bgc_zoop_raw"]
                }
            ]
        }
    }
}
```

_handler.py_
```python
#!/usr/bin/env python
import os

from aodncore.pipeline import HandlerBase, PipelineFilePublishType, FileType, PipelineFileCollection, PipelineFile
# from aodncore.pipeline.exceptions import InvalidFileNameError, InvalidFileContentError


class BgcHandler(HandlerBase):
    def __init__(self, *args, **kwargs):
        super(BgcHandler, self).__init__(*args, **kwargs)
        self.allowed_extensions = ['.zip', '.csv']
        self.harvest_type = 'csv'

    def dest_path(self, filepath):
        """
        Destination object path for the BGC test .zip file or the individual .csv files.
        """

        base_path = "IMOS/BGC"
        dest_path = os.path.join(base_path, os.path.basename(filepath))
        return dest_path

```

_bgc.sql_
```sql
CREATE ROLE bgc LOGIN
  NOSUPERUSER INHERIT NOCREATEDB NOCREATEROLE NOREPLICATION  PASSWORD 'bgc';
GRANT harvest_read_group TO bgc;
GRANT harvest_reporting_write_group TO bgc;
GRANT harvest_write_group TO bgc;

GRANT bgc TO imosadmin;

CREATE SCHEMA bgc
  AUTHORIZATION bgc;
```

_database.json_
```json
{
    "dbname": "harvest",
    "host": "harvest-db-natetest.dev.aodn.org.au",
    "port": "5432",
    "user": "bgc",
    "password": "bgc",
    "options": "-c search_path=bgc"
}

```

**Comment by ndhogan** [comment]
> * there aren't any unittests
> * docstrings/comments are generally missing (I think they are semi-automatically used in the generation of the doc, https://aodn.github.io/python-aodncore/index.html)
> * are we going to use liquibase and keep the same existing common tables (such as indexed_file) available in each schema?  

It's still very much a work in progress, I'll be adding unittests and docstrings over the rest of the iteration, and we have 2 more bits of functionality to add in the next iteration... but I created the draft PR so @mhidas could have an early look if he wanted.

> also FYI, I see you wanted to use environment variables. Correct me if I'm wrong, but I think for this we usually use variables defined in chef-private under https://github.com/aodn/chef-private/blob/master/data_bags/pipeline/pipeline_conf_rc.json

Ah yes, Marty mentioned this - I see now that this is the practice, so will follow suit

**Comment by mhidas** [comment]
> As far as I'm aware liquibase won't need to be used for this specific harvester runner - as we'll use the schema definitions in public-schema to build the table create sql. I'm not sure about the common tables - @mhidas?

That's right. For the Octopus/BGC/Water sampling DB, as long as we're always dropping and re-creating all the tables every time, we don't really _need_ any of the common (indexing) tables maintained by Talend harvesters.

However, we have talked about the possibility of including at least a version of `indexed_file`, to keep track of what was harvested, and when. Add such a table will become more important if we ever want this harvester to support more complicated operations, such as
* incremental ingest (appending data from a CSV file without first dropping the target table); or
* delete/unharvest (dropping only rows that were harvested from a specific file).

In that case we'll also need to add foreign keys to each harvested table, linking each row to a particular `indexed_file`.

**Comment by mhidas** [comment]
@ndhogan I am trying to run the harvester in my pipeline box. It seems to set up the pipeline ok, but when I put a file in, I get
```
2021-07-26 03:03:17,307 SYSINFO tasks.BGC[ac049cbd-aa27-41be-82fa-1fb28b55f71b] get_harvester_runner -> CsvHarvesterRunner()
2021-07-26 03:03:17,791 ERROR tasks.BGC[ac049cbd-aa27-41be-82fa-1fb28b55f71b] InvalidSQLConnectionError: FATAL:  database "harvest?loginTimeout=1000&ssl=true&sslfactory=org.postgresql.ss" does not exist
Traceback (most recent call last):
  File "/vagrant/src/python-aodncore/aodncore/pipeline/db.py", line 59, in __connect
    return psycopg2.connect(**params)
  File "/mnt/ebs/pipeline/lib/python3.5/site-packages/psycopg2/__init__.py", line 127, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: FATAL:  database "harvest?loginTimeout=1000&ssl=true&sslfactory=org.postgresql.ss" does not exist
```
Looks like the db connection string is truncated.
In `/usr/local/harvester/bgc/database.json` I have
```
{"host":"harvest-db-aodnstack-mhidas.dev.aodn.org.au","dbname":"harvest?loginTimeout=1000&ssl=true&sslfactory=org.postgresql.ssl.NonValidatingFactory","port":"5432","user":"bgc","password":"bgc","options":"-c search_path=bgc, public"}
```
The content is seems right according to https://github.com/aodn/chef/pull/1111#issue-688470518, but it's all on one line - not sure if that's relevant?

**Comment by ndhogan** [comment]
@mhidas - ah damn, I thought I reversed that change... does it work if you manually change the "dbname" attribute to "harvest"?

**Comment by mhidas** [comment]
@ndhogan Thanks. Yes, that gets me past that error.
I also had to edit the "options" attribute to remove the space after the comma, otherwise I would get
`InvalidSQLConnectionError: FATAL:  invalid value for parameter "search_path": "bgc,"`

So now it seems to connect ok, with the updated `database.json` as
```
{
    "host":"harvest-db-aodnstack-mhidas.dev.aodn.org.au",
    "dbname":"harvest",
    "port":"5432",
    "user":"bgc",
    "password":"bgc",
    "options":"-c search_path=bgc,public"
}
```

**Comment by ndhogan** [comment]
Thanks @mhidas 

@ccmoloney - small fix, 2 lines of code in _cookbooks/harvester/providers/job.rb_ I've added backlog item https://github.com/aodn/backlog/issues/3286 and provisionally scored at 1/2 story point

**Comment by mhidas** [comment]
Ok, I've got the validation working :+1:
And it's connecting to the db :+1: 
But when it now fails trying to create the table
```
2021-07-26 06:08:42,117 SYSINFO tasks.BGC[8ed9b2ed-9aa8-4837-bd6a-ccc1ccec4947] get_harvester_runner -> CsvHarvesterRunner()
2021-07-26 06:08:42,473 INFO tasks.BGC[8ed9b2ed-9aa8-4837-bd6a-ccc1ccec4947] Compare schema not yet implemented...
2021-07-26 06:08:42,473 INFO tasks.BGC[8ed9b2ed-9aa8-4837-bd6a-ccc1ccec4947] Using process sequence `replace`
2021-07-26 06:08:42,475 INFO tasks.BGC[8ed9b2ed-9aa8-4837-bd6a-ccc1ccec4947] Executing steps for bgc_trip
2021-07-26 06:08:42,475 INFO tasks.BGC[8ed9b2ed-9aa8-4837-bd6a-ccc1ccec4947] Dropping table bgc_trip
2021-07-26 06:08:42,561 INFO tasks.BGC[8ed9b2ed-9aa8-4837-bd6a-ccc1ccec4947] Creating table bgc_trip
2021-07-26 06:08:42,607 INFO tasks.BGC[8ed9b2ed-9aa8-4837-bd6a-ccc1ccec4947] Rolling back changes
2021-07-26 06:08:42,635 ERROR tasks.BGC[8ed9b2ed-9aa8-4837-bd6a-ccc1ccec4947] InvalidSQLTransactionError: column "t" named in key does not exist
LINE 1: ..._MGM3 numeric,SECCHI_M numeric,SAMPLETYPE varchar,PRIMARY KE...
                                                             ^
Traceback (most recent call last):
  File "/vagrant/src/python-aodncore/aodncore/pipeline/db.py", line 72, in __exec
    self._cur.execute(sql.SQL(statement))
psycopg2.errors.UndefinedColumn: column "t" named in key does not exist
LINE 1: ..._MGM3 numeric,SECCHI_M numeric,SAMPLETYPE varchar,PRIMARY KE...
                                                             ^


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/vagrant/src/python-aodncore/aodncore/pipeline/handlerbase.py", line 1054, in run
    self.trigger(transition['trigger'])
  File "/mnt/ebs/pipeline/lib/python3.5/site-packages/transitions/core.py", line 859, in _get_trigger
    return event.trigger(model, *args, **kwargs)
  File "/mnt/ebs/pipeline/lib/python3.5/site-packages/transitions/core.py", line 393, in trigger
    return self.machine._process(func)
  File "/mnt/ebs/pipeline/lib/python3.5/site-packages/transitions/core.py", line 1148, in _process
    return trigger()
  File "/mnt/ebs/pipeline/lib/python3.5/site-packages/transitions/core.py", line 411, in _trigger
    return self._process(event_data)
  File "/mnt/ebs/pipeline/lib/python3.5/site-packages/transitions/core.py", line 420, in _process
    if trans.execute(event_data):
  File "/mnt/ebs/pipeline/lib/python3.5/site-packages/transitions/core.py", line 268, in execute
    event_data.machine.callbacks(itertools.chain(event_data.machine.before_state_change, self.before), event_data)
  File "/mnt/ebs/pipeline/lib/python3.5/site-packages/transitions/core.py", line 1083, in callbacks
    self.callback(func, event_data)
  File "/mnt/ebs/pipeline/lib/python3.5/site-packages/transitions/core.py", line 1104, in callback
    func(*event_data.args, **event_data.kwargs)
  File "/vagrant/src/python-aodncore/aodncore/pipeline/handlerbase.py", line 783, in _publish
    self._harvest()
  File "/vagrant/src/python-aodncore/aodncore/pipeline/handlerbase.py", line 747, in _harvest
    harvest_runner.run(files_to_harvest)
  File "/vagrant/src/python-aodncore/aodncore/pipeline/steps/harvest.py", line 449, in run
    getattr(conn, task)(step)
  File "/vagrant/src/python-aodncore/aodncore/pipeline/db.py", line 189, in create_table_from_yaml_file
    self.__exec('CREATE TABLE {} ({})'.format(step['name'], ','.join(columns)))
  File "/vagrant/src/python-aodncore/aodncore/pipeline/db.py", line 74, in __exec
    raise InvalidSQLTransactionError(error)
aodncore.pipeline.exceptions.InvalidSQLTransactionError: column "t" named in key does not exist
LINE 1: ..._MGM3 numeric,SECCHI_M numeric,SAMPLETYPE varchar,PRIMARY KE...
                                                             ^
```
The primary key for this table should be "TRIP_CODE", so maybe it's only getting the first letter for some reason?

**Pull request closed without merging**
