### PR TITLE
PR to deploy WSD changes

### PR DESCRIPTION
**Pull request by digorgonzola**

### CODE REVIEW

**Comment by mhidas** [comment]
@ndhogan Humph... some of the unittests are failing.

**Comment by mhidas** [comment]
And while I think of it, I think this adds sufficient new functionality to justify a minor version bump. @ndhogan

**Comment by ndhogan** [comment]
> @ndhogan Humph... some of the unittests are failing.

Possibly the missing leading forward slash in REFERENCE_PIPELINE_CONFIG.harvester ?

**Comment by mhidas** [comment]
That fixed the first error, but two more still failing 
```
=========================== short test summary info ============================
FAILED test_aodncore/pipeline/test_schema.py::TestPipelineSchema::test_validate_harvest_params_nodbobjects
FAILED test_aodncore/pipeline/test_schema.py::TestPipelineSchema::test_validate_harvest_params_noschema
================= 2 failed, 422 passed, 245 warnings in 30.86s =================
```

**Comment by ndhogan** [comment]
> That fixed the first error, but two more still failing
> 
> ```
> =========================== short test summary info ============================
> FAILED test_aodncore/pipeline/test_schema.py::TestPipelineSchema::test_validate_harvest_params_nodbobjects
> FAILED test_aodncore/pipeline/test_schema.py::TestPipelineSchema::test_validate_harvest_params_noschema
> ================= 2 failed, 422 passed, 245 warnings in 30.86s =================
> ```

OK, so it looks like somewhere between jsonschema 3.2.0 and 4.1.2 the _dependencies_ method has been split into _dependentRequired_ and _dependentSchemas_

We could add a jsonschema constraint (eg. <3.2.1)?

**Comment by mhidas** [comment]
> We could add a jsonschema constraint (eg. <3.2.1)?

Sure. In the prod pipeline environment we actually still have 2.6.0 because of a constraint in [aodntools](https://github.com/aodn/python-aodntools/blob/558c0da541ce96bd67d5be98c49833b5b1fee22d/setup.py#L4)

**Comment by ndhogan** [comment]
PR for step 4 of runsheet

Stage | Step | Description | Actor | Rollback plan | Description / Additional
-- | -- | -- | -- | -- | --
RC deploy | 4 | Merge python-aodncore [wsd] --> [master] | Devs | Revert merge |  

https://github.com/aodn/backlog/issues/3414

**Review by nspool — APPROVED** [review]

**Pull request merged**
