### PR TITLE
Add validate_unique parameter to PipelineFileCollection, to allow dup…

### PR DESCRIPTION
**Pull request by lwgordonimos**
…licate checking to be disabled

### CODE REVIEW

**Comment by kereid** [comment]
resolved by https://github.com/aodn/issues/issues/851

**Review by anguss00 — APPROVED** [review]

**Comment by mhidas** [comment]
@lwgordonimos @lbesnard Was this PR actually needed for anything? The updated version of aodncore (1.1.5) was never even deployed to RC, let alone prod!

Just asking because I've just merged #216, which will improve legibility of the pipeline logs, and it would be nice to test & deploy that (now v1.1.6).

**Comment by mhidas** [comment]
For now I've just promoted 1.1.5 to RC

**Comment by lwgordonimos** [comment]
@mhidas it is just a performance optimisation, so should be transparent (other than being faster for large collection sizes). So other than general regression testing, it shouldn't need any special attention.

**Comment by mhidas** [comment]
:+1: Ok. I've tested and promoted 1.1.5 to prod.

**Pull request merged**
